### PR TITLE
Fix tracking entity

### PR DESCRIPTION
**Pull request by jjohxx**

### CODE REVIEW

**Comment by jjohxx** [comment]
Hey! you need to focus on lines 64 - 70

**Comment by jounger** [comment]
Thank you, that's work!!!

**Comment by jjohxx** [comment]
You're welcome, anything you can ping me

**Comment by jounger** [comment]
Hi jjohxx,
After solved POST, I think PUT is the same but when I try to PUT an object (change Tracking's title) and it return 400 Bad Request. What's really happended on my code? Please check it!
`	@RequestMapping("/trackings/edit/{id}")
	public String editTrackingByOrderId(@PathVariable String id) {
		String url = "https://api.aftership.com/v4/trackings/dhl/7835112123"; // fixed id, just for test
		MainTracking mainTracking = new MainTracking();
        Tracking tracking = new Tracking();
        tracking.setTitle("Fuck this shit");
        tracking.setOrder_id("test123");
        mainTracking.setTracking(tracking);
        RestTemplate restTemplate = new RestTemplate();
        HttpEntity<MainTracking> entity = new HttpEntity<MainTracking>(mainTracking, HttpHeaderConfig());
        ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.GET, entity, String.class);
        restTemplate.put(url, entity);
        return response.getBody().toString();
	}`

**Comment by jounger** [comment]
I also updated my code in repository, follow this link:
https://github.com/jounger/aftership-api-test/blob/master/aftership-api-1/src/main/java/api/aftership/tracking/TrackingController.java

**Comment by jjohxx** [comment]
@jounger do you still have the update issue?

**Comment by jounger** [comment]
Oh good to see you again, hope you have little free time ^^.
 I still stuck with it, I tried sent it by json, correct format but not
work at all with resttemplate. How can I solve it?


*Name:  Nguyễn Văn An*
*Jobs:  Web designer, Blogger, etc.*
*Studied: Kỹ sư CNTT tại Trường Đại học FPT*
*Mobile: +84-967 390 098*
*Email:  nguyenvanan.12a8@gmail.com <nguyenvanan.12a8@gmail.com>*
*Blog:  Toisong.com <http://toisong.com/>*
*Address: KM29 Đại Lộ Thăng Long, Thạch Hoà, Thạch Thất, Khu GD&ĐT, Khu CNC
Hòa Lạc Hà Nội*



Vào Th 4, 2 thg 1, 2019 vào lúc 09:41 Jhonatan Mamani <
notifications@github.com> đã viết:

**Comment by jounger** [comment]
Update with PUT method not work


*Name:  Nguyễn Văn An*
*Jobs:  Web designer, Blogger, etc.*
*Studied: Kỹ sư CNTT tại Trường Đại học FPT*
*Mobile: +84-967 390 098*
*Email:  nguyenvanan.12a8@gmail.com <nguyenvanan.12a8@gmail.com>*
*Blog:  Toisong.com <http://toisong.com/>*
*Address: KM29 Đại Lộ Thăng Long, Thạch Hoà, Thạch Thất, Khu GD&ĐT, Khu CNC
Hòa Lạc Hà Nội*



Vào Th 4, 2 thg 1, 2019 vào lúc 16:47 V An. <nguyenvanan.12a8@gmail.com>
đã viết:

**Comment by jjohxx** [comment]
Do you still have the issue? xD hi if it is, please send me an email to johxgks@gmail.com with description on your issue...

**Pull request merged**
